version: '3'

services:

  #MongoDB
  mongodb_service:
    container_name: databse_container
    image: mongo:latest
    restart: always
    volumes:
        - mongodb_service:/data/db
  #Server
  api:
    container_name: server
    restart: always
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    env_file: .env
    depends_on:
      - mongodb_service

volumes:
  mongodb_service:


